"""
Main entrypoint file for the entire workflow for custom problems.
Including a workflow from test plan --> implementation --> run tests
because the tests are generated by LLMs here for real world SWE problems.
"""

import json
import shutil
import argparse
from pathlib import Path
import subprocess
from typing import Callable
from ..auth.codex_login import CodexLogin
from ..BwrapExecutor import BwrapExecutor
from ..get_prompt_and_run_agent import get_prompt_and_run_agent
from validators.module_name_validator import module_name_validator
from write_metrics.write_metrics_from_design_and_deps_graph import (
    write_metrics_from_design_and_deps_graph,
)
from metrics.deps_graph.bfs import bfs_get_modules_to_implement
from write_metrics.write_metrics_from_implementation import (
    write_metrics_from_implementation,
)
from ..settings import WORKFLOW_MODE, AGENT, MODEL, PROBLEM_TYPE, UI_ENABLED
from ..entry_files import ENTRY_FILES
from scripts.pytest_scb import pytest_scb
from json_schemas.formatters.design_formatter import get_design_summary
from typing import Any
from .ui_text_formatters import (
    get_formatted_design,
    get_formatted_implementation,
    get_formatted_analyzer_suggestions,
    get_formatted_deps_graph,
)


# Stop the background running agent subprocess
# Only triggered when ui is enabled
def stop_run_agent_processes() -> None:
    subprocess.run(
        ["pkill", "-f", "workspace_helpers.run_agent"],
        check=False,
    )


# Constants for directory and file paths
SUFFIX = f"{WORKFLOW_MODE}_{AGENT}_{MODEL}"  # used by both agent workspace and implementation dest 
AGENT_TEST_STORAGE = Path(
    "agent_test_storage"
)  # temp storage for tests, not visible in agent workspace
PROBLEMS_DIR = (
    Path("datasets/custom/problems")
    if PROBLEM_TYPE == "custom"
    else Path("datasets/slopCodeBench/scb-problems")
)
WORKSPACE_HELPERS = Path("modular_main/workspace_helpers")
SETTINGS_PATH = Path("modular_main/settings.py")

StageCallback = Callable[[str], None]
SettingsCallback = Callable[[dict[str, Any]], None]
AgentResponseCallback = Callable[[str], None]
DesignOrImplCallback = Callable[[dict[str, Any]], None]
AnalyzerSuggestionsCallback = Callable[[list[Any]], None]
RequirementsCallback = Callable[[dict[str, Any]], None]
DepsGraphCallback = Callable[[dict[str, Any]], None]


def _report_stage(stage_callback, stage) -> None:
    if stage_callback is not None:
        stage_callback(stage)


def _report_settings(settings_callback, settings):
    if settings_callback is not None:
        settings_callback(settings)


def _report_agent_response(
    agent_response_callback: AgentResponseCallback | None,
    agent_response: str,
) -> None:
    if agent_response_callback is not None:
        agent_response_callback(agent_response)


def _report_design_or_impl(
    design_or_impl_callback: DesignOrImplCallback | None,
    design_or_impl: dict[str, Any],
) -> None:
    if design_or_impl_callback is not None:
        design_or_impl_callback(design_or_impl)


def _report_analyzer_suggestions(
    analyzer_suggestions_callback: AnalyzerSuggestionsCallback | None,
    analyzer_suggestions: list[Any],
) -> None:
    if analyzer_suggestions_callback is not None:
        analyzer_suggestions_callback(analyzer_suggestions)


def _report_requirements(
    requirements_callback: RequirementsCallback | None,
    requirements: dict[str, Any],
) -> None:
    if requirements_callback is not None:
        requirements_callback(requirements)


def _report_deps_graph(
    deps_graph_callback: DepsGraphCallback | None, deps_graph: dict[str, Any]
) -> None:
    if deps_graph_callback is not None:
        deps_graph_callback(deps_graph)


# Constants for the modular workflow
DA_LOOP_THRESHOLD_BEFORE_IMPL = 2  # how many times can the D <> A Loop happen
DA_LOOP_THRESHOLD_AFTER_IMPL = 2  # how many times can the A <> R loop happen - refers to how many times the RC agent can be invoked
TR_LOOP_THRESHOLD = 2  # How many times the tester - test refactor coder loop happen

# set the thresholds to infinite if human mode
if WORKFLOW_MODE == "human":
    DA_LOOP_THRESHOLD_BEFORE_IMPL = 555
    DA_LOOP_THRESHOLD_AFTER_IMPL = 555


# function to format code inside agent_workspace / implementation
# by running prettier (ts, json) and black (Python)
def _format_code(agent_workspace):
    implementation_path = agent_workspace / "implementation"

    # run prettier
    subprocess.run(
        [
            "npx",
            "prettier",
            "--write",
            implementation_path,
            "--ignore-path",
            "/dev/null",
        ],
        check=True,
    )

    # run black
    subprocess.run(
        [
            "bash",
            "-c",
            f'find {implementation_path} -name "*.py" -print0 | xargs -0 black',
        ],
        check=True,
    )


# Function to decide whether to pass or fail, given the analyzer output.
def _pass_fail(agent_workspace):
    # Read the current analyzer.json. If there are no unresolved issue, automatically set to pass
    with open(agent_workspace / "current_analyzer_result.json", "r") as f:
        content = f.read().strip()
        # if the content is empty, then set the result to []. Else, load json
        # this wont raise an error if the file is empty
        analyzer_result = json.loads(content) if content else []
        if len([x for x in analyzer_result if x["status"] == "unresolved"]) == 0:
            return True

    # if there are any unresolved issues, then fail
    return False


# pipeline to run decomposer + validate
def _run_decomposer(
    executor,
    checkpoint_number,
    agent_workspace,
    design_or_impl_callback=None,
    deps_graph_callback=None,
    agent_response_callback=None,
):
    output = get_prompt_and_run_agent(executor, "decomposer", checkpoint_number)

    # reflect in the UI the agent output
    _report_agent_response(agent_response_callback, output)

    # Validator for the module names
    print(f"========== VALIDATOR FOR MODULE NAMES ==========")
    v_output = module_name_validator(
        agent_workspace / "current_design.json",
        agent_workspace / "current_deps_graph.json",
    )

    # Currently, if this array is non empty, throw an error
    v_output_list = list(v_output)
    if v_output_list:
        print(v_output_list)
        raise Exception(f"Validator failed: \n{v_output_list}")
    print("Passed")

    # Write the current deps graph SVG
    deps_graph_json_path = agent_workspace / "current_deps_graph.json"
    if deps_graph_json_path.exists():
        subprocess.run(
            [
                "python",
                "scripts/deps_graph_json_to_svg.py",
                deps_graph_json_path,
                "-o",
                agent_workspace / "current_deps_graph",
            ],
            capture_output=True,
            text=True,
        )

    # Reflect in the UI the updated current design
    _report_design_or_impl(
        design_or_impl_callback, get_formatted_design(agent_workspace)
    )

    # Reflect in UI the updated deps graph
    _report_deps_graph(deps_graph_callback, get_formatted_deps_graph(agent_workspace))


# pipeline to run analyzer + write analyzer suggestions
def _run_analyzer(executor, analyzer_suggestions_callback=None):
    pass


# Decomposer analyzer loop.
# D first before A
# for has impl = False only.
def _decomposer_analyzer_loop(
    executor,
    checkpoint_number,
    threshold,
    agent_workspace,
    stage_callback=None,
    design_or_impl_callback=None,
    analyzer_suggestions_callback=None,
    agent_response_callback=None,
    deps_graph_callback=None,
):
    iteration = 0
    passed = False

    # Initial decomposer agent
    print(f"========== INITIAL DECOMPOSER AGENT ==========")
    _report_stage(stage_callback, "Initial decomposer agent")
    _run_decomposer(
        executor,
        checkpoint_number,
        agent_workspace,
        design_or_impl_callback=design_or_impl_callback,
        deps_graph_callback=deps_graph_callback,
        agent_response_callback=agent_response_callback,
    )

    while not passed and iteration < threshold:
        # Generate metrics from design and deps graph
        print(f"========== [Iteration {iteration+1}] GENERATE METRICS ==========")
        _report_stage(stage_callback, f"(Iteration {iteration+1}) Generate metrics")
        write_metrics_from_design_and_deps_graph(
            agent_workspace / "current_design.json",
            agent_workspace / "current_deps_graph.json",
            agent_workspace / "current_metrics.json",
        )

        # Analyzer agent
        print(f"========== [Iteration {iteration+1}] ANALYZER AGENT ==========")
        _report_stage(stage_callback, f"(Iteration {iteration+1}) Analyzer agent")
        if WORKFLOW_MODE == "human":
            output = get_prompt_and_run_agent(executor, "analyzer_human", False)
        elif WORKFLOW_MODE in ["auto", "autoNoMetric", "autoTest", "autoAggressive", "autoByLayer"]:
            output = get_prompt_and_run_agent(
                executor, "analyzer", False
            )  # has impl = False

        # Reflect the analyzer suggestions
        _report_analyzer_suggestions(
            analyzer_suggestions_callback,
            get_formatted_analyzer_suggestions(agent_workspace),
        )

        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # After the analyzer runs, make the current_analyzer_result.json if it does not exist
        analyzer_result_path = agent_workspace / "current_analyzer_result.json"
        if not analyzer_result_path.exists():
            analyzer_result_path.touch()

        # If the analyzer return pass, set the passed flag to true
        if _pass_fail(agent_workspace):
            passed = True

        # if passed, return
        if passed:
            return

        # Else if it does not pass (here), run the decomposer agent
        print(f"========== [Iteration {iteration+1}] DECOMPOSER AGENT ==========")
        _report_stage(stage_callback, f"(Iteration {iteration+1}) Decomposer agent")
        _run_decomposer(
            executor,
            checkpoint_number,
            agent_workspace,
            design_or_impl_callback=design_or_impl_callback,
            deps_graph_callback=deps_graph_callback,
            agent_response_callback=agent_response_callback,
        )

        # Increment the iteration number
        iteration += 1


# Test Refactor - Tester loop: Happens after implementation within the AR loop.
def _tester_refactor_loop(
    executor,
    checkpoint_number,
    threshold,
    agent_workspace,
    agent_test_storage, 
    stage_callback: StageCallback | None = None,
    design_or_impl_callback: DesignOrImplCallback | None = None,
    agent_response_callback: AgentResponseCallback | None = None,
):
    iteration = 0
    passed = False

    while not passed and iteration < threshold:
        # Move the blueprint and tests folder into the agent workspace
        if (agent_test_storage / "test_blueprint.json").exists():
            shutil.move(agent_test_storage / "test_blueprint.json", agent_workspace)
        if (agent_test_storage / "tests").exists():
            shutil.move(agent_test_storage / "tests", agent_workspace)

        # Call the tester agent
        print(
            f"========== [Iteration {iteration+1}] WRITING AND RUNNING TESTS =========="
        )
        _report_stage(
            stage_callback, f"(Iteration {iteration+1}) Writing and running tests"
        )
        output = get_prompt_and_run_agent(executor, "tester", checkpoint_number)
        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # Move the blueprint and tests outside the agent workspace.
        # This is so the test content and function signatures dont get leaked to the coders
        if (agent_workspace / "test_blueprint.json").exists():
            shutil.move(agent_workspace / "test_blueprint.json", agent_test_storage)
        if (agent_workspace / "tests").exists():
            shutil.move(agent_workspace / "tests", agent_test_storage)

        # Remove the report - it describes the test intention that cant be leaked to coders
        (agent_workspace / "agent_report.json").unlink()

        # Check the written current_test_results.json to discover if there are any failed tests
        print(f"========== ANALYZING TEST RESULTS ==========")
        _report_stage(stage_callback, "Analyzing test results")
        with open(agent_workspace / "current_test_results.json", "r") as f:
            test_results_json = json.load(f)

            passed_tests = len([x for x in test_results_json if x["result"] == "pass"])
            failed_tests = len([x for x in test_results_json if x["result"] == "fail"])

            results = f"{passed_tests} passed, {failed_tests} failed."
            print(results)
            _report_stage(stage_callback, results)

        # if there are no failed tests, set passed = true
        if failed_tests == 0:
            passed = True

        else:
            # else call the test refactorer
            print(
                f"========== [Iteration {iteration+1}] TEST REFACTOR AGENT =========="
            )
            _report_stage(
                stage_callback, f"(Iteration {iteration+1}) Test refactor agent"
            )
            output = get_prompt_and_run_agent(
                executor, "test_refactor_coder", checkpoint_number
            )
            # reflect in the UI the agent output
            _report_agent_response(agent_response_callback, output)

            # format code
            _format_code(agent_workspace)

            # reflect the updated code in the UI
            _report_design_or_impl(
                design_or_impl_callback, get_formatted_implementation(agent_workspace)
            )

        iteration += 1


# Refactor analyzer loop - happens after implementation.
# A first before R
# For has impl = True only.
# Loop:
# Run tests and fix code --> Update metrics --> Analyzer -->
def _analyzer_refactor_loop(
    executor,
    checkpoint_number,
    threshold,
    agent_workspace,
    agent_test_storage, 
    stage_callback: StageCallback | None = None,
    design_or_impl_callback: DesignOrImplCallback | None = None,
    analyzer_suggestions_callback: AnalyzerSuggestionsCallback | None = None,
    deps_graph_callback: DepsGraphCallback | None = None,
    agent_response_callback=None,
):
    # After coding: Run tests
    def tester_agent(agent_workspace):
        print(f"========== TESTER ==========")
        _report_stage(stage_callback, "Tester")

        # Move tests from the storage to the workspace
        if (agent_test_storage / "tests").exists():
            shutil.move(agent_test_storage / "tests", agent_workspace)

        output = get_prompt_and_run_agent(
            executor, "test_refactor_coder", checkpoint_number
        )
        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # Move tests back to the external storage
        if (agent_workspace / "tests").exists():
            shutil.move(agent_workspace / "tests", agent_test_storage)

        # Remove the report - it describes the test intention that cant be leaked to coders
        (agent_workspace / "agent_report.json").unlink()

        # Remove the pytest cache path - it also exposes the test intention
        pytest_cache = agent_workspace / ".pytest_cache"
        if pytest_cache.exists():
            shutil.rmtree(pytest_cache)

    # update current_metrics.json using the implementation
    def update_metrics(agent_workspace):
        # Update the dependency graph
        print(
            f"========== [Iteration {iteration+1}] UPDATE DEPENDENCY GRAPH =========="
        )
        _report_stage(
            stage_callback, f"(Iteration {iteration+1}) Update dependency graph"
        )
        subprocess.run(
            [
                "python",
                "scripts/deps_graph.py",
                agent_workspace / "implementation",
                agent_workspace / "deps_graphs",
            ],
            check=True,
        )

        # Extract only the json and svg, and also the visibility matrix json and png
        shutil.copy(
            agent_workspace / "deps_graphs" / "deps_graph.json",
            agent_workspace / "current_deps_graph.json",
        )  # Replace the current deps graph json

        shutil.copy(
            agent_workspace / "deps_graphs" / "deps_graph.svg",
            agent_workspace / "current_deps_graph.svg",
        )  # Generate a new svg file

        # Reflect new deps graph in the UI
        _report_deps_graph(
            deps_graph_callback, get_formatted_deps_graph(agent_workspace)
        )

        shutil.copy(
            agent_workspace / "deps_graphs" / "matrix.json",
            agent_workspace / "matrix.json",
        )

        shutil.copy(
            agent_workspace / "deps_graphs" / "matrix.png",
            agent_workspace / "matrix.png",
        )

        # Remove the temp deps_graph/ directory
        shutil.rmtree(agent_workspace / "deps_graphs")

        # Generate metrics using the actual implementation
        print(f"========== [Iteration {iteration+1}] GENERATE METRICS ==========")
        _report_stage(
            stage_callback, f"(Iteration {iteration+1}) Generate implementation metrics"
        )

        # Write metrics from implementation - include the previous implementation if it exists
        write_metrics_from_implementation(
            implementation_path=agent_workspace / "implementation",
            current_metrics_path=agent_workspace / "current_metrics.json",
            prev_implementation_path=(
                agent_workspace / "previous_implementation"
                if (agent_workspace / "previous_implementation").exists()
                else None
            ),
        )

    iteration = 0
    passed = False

    # Initial decomposer agent
    # Run these inside the bind mounted space
    while not passed and iteration < threshold:
        # run tests
        if WORKFLOW_MODE == "autoTest":
            tester_agent(agent_workspace)

        # write metrics from impl if workflow is not nometric
        if WORKFLOW_MODE != "autoNoMetric":
            update_metrics(agent_workspace)

        # Analyzer agent
        print(f"========== [Iteration {iteration+1}] ANALYZER AGENT ==========")
        _report_stage(stage_callback, f"(Iteration {iteration+1}) Analyzer agent")
        if WORKFLOW_MODE == "human":
            output = get_prompt_and_run_agent(executor, "analyzer_human", True)
        elif WORKFLOW_MODE in ["auto", "autoNoMetric", "autoTest", "autoAggressive", "autoByLayer"]:
            output = get_prompt_and_run_agent(
                executor, "analyzer", True
            )  # has impl = True

        # Reflect the analyzer suggestions
        _report_analyzer_suggestions(
            analyzer_suggestions_callback,
            get_formatted_analyzer_suggestions(agent_workspace),
        )

        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # After the analyzer runs, make the current_analyzer_result.json if it does not exist
        analyzer_result_path = agent_workspace / "current_analyzer_result.json"

        if not analyzer_result_path.exists():
            analyzer_result_path.touch()

        # If the analyzer return pass, set the passed flag to true
        # a_output_json = json.loads(a_output)
        # print(json.dumps(a_output_json, indent=2))
        if _pass_fail(agent_workspace):
            passed = True

        # if passed, return
        if passed:
            return

        # if not passed, then call the refactor agent
        print(f"========== [Iteration {iteration+1}] REFACTOR CODER AGENT ==========")
        _report_stage(stage_callback, f"(Iteration {iteration+1}) Refactor coder agent")
        output = get_prompt_and_run_agent(executor, "refactor_coder", checkpoint_number)

        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # format code
        _format_code(agent_workspace)

        # reflect the updated code in the UI
        _report_design_or_impl(
            design_or_impl_callback, get_formatted_implementation(agent_workspace)
        )

        # Increment the iteration number
        iteration += 1

    # Once the loop ends because it hits the threshold, invoke the update metrics function again to show the latest changes to the metrics
    # this is unaffected by the workflow mode - for developer see only, not for agents to see.
    if iteration == threshold:
        update_metrics(agent_workspace)


# main entrypoint of the modular workflow
# usage: python -m modular_main.main <problem_name> <checkpoint_number>
def modular_workflow_single(
    problem,
    n,
    logged_in=False,  # so it does not re-log in in multiple stages run
    stage_callback=None,
    settings_callback=None,
    design_or_impl_callback=None,
    agent_response_callback=None,
    analyzer_suggestions_callback=None,
    requirements_callback=None,
    deps_graph_callback=None,
):

    # Obtain the problem name and checkpoint no
    PROBLEM = problem
    N = n

    # Modify the agent workspace names so the code can run concurrently 
    AGENT_WORKSPACE = Path(f"agent_workspace_{PROBLEM}_{N}_{SUFFIX}")
    AGENT_TEST_STORAGE = Path(f"agent_test_storage_{PROBLEM}_{N}_{SUFFIX}")

    # For scb problems only: if the problem name is not in the list of entry files,
    # raise an exception
    if PROBLEM_TYPE == "scb" and PROBLEM not in ENTRY_FILES:
        raise Exception(f"Invalid SCB problem name: {PROBLEM}")
    ENTRY_FILE_NAME = ENTRY_FILES[PROBLEM] if PROBLEM_TYPE == "scb" else None

    # Get the problem dir
    PROBLEM_DIR = PROBLEMS_DIR / PROBLEM

    # if the problem dir does not exist, raise exception
    if not PROBLEM_DIR.exists():
        raise Exception(f"Invalid problem: {PROBLEM}")
    PROBLEM_IMPL_DIR = (
        PROBLEM_DIR / f"implementations_{SUFFIX}"
    )  # Previous implementation depend on the workflow mode
    REPORT_DIR = (
        PROBLEM_DIR / f"report_{SUFFIX}"
    )  # agent reports
    PREV_IMPL = PROBLEM_IMPL_DIR / f"checkpoint_{N-1}"
    PROBLEM_INSTRUCTIONS = PROBLEM_DIR / f"checkpoint_{N}.md"

    # Create the problem impl dir and report dir
    PROBLEM_IMPL_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    # Print the workflow mode
    print(f"AGENT: {AGENT}")
    print(f"MODEL: {MODEL}")
    print(f"MODE: {WORKFLOW_MODE}")
    print(f"PROBLEM TYPE: {PROBLEM_TYPE}")
    print(f"PROBLEM NAME: {PROBLEM}")
    print(f"CHECKPOINT: {N}")
    print("=" * 20)

    # Mark the settings inside ui
    _report_settings(
        settings_callback,
        {
            "problem_type": PROBLEM_TYPE,
            "problem_name": PROBLEM,
            "workflow_mode": WORKFLOW_MODE,
            "agent": AGENT,
            "model": MODEL,
            "checkpoint": N,
        },
    )

    # Step 1: Create the agent workspace and test storage
    print("[MAIN 1/8] Creating agent workspace")
    _report_stage(stage_callback, "Creating agent workspace")
    if AGENT_WORKSPACE.exists():
        shutil.rmtree(AGENT_WORKSPACE)  # rmdir -r
    AGENT_WORKSPACE.mkdir(exist_ok=True)  # mkdir -p

    # activate agent test storage in autoTest mode only 
    if WORKFLOW_MODE == "autoTest": 
        if AGENT_TEST_STORAGE.exists():
            shutil.rmtree(AGENT_TEST_STORAGE)
        AGENT_TEST_STORAGE.mkdir(exist_ok=True)

    # Step 2: Copy the workspace_helpers folder to the agent workspace
    print("[MAIN 2/8] Copying helper functions to agent workspace")
    _report_stage(stage_callback, "Copying helper functions to agent workspace")
    shutil.copytree(WORKSPACE_HELPERS, AGENT_WORKSPACE / "workspace_helpers")

    # Also copy settings.py, as run_agent needs it whether UI is enabled
    shutil.copy(SETTINGS_PATH, AGENT_WORKSPACE)

    # Step 3: Copy the required files to the agent workspace
    print("[MAIN 3/8] Copying files to agent workspace")
    _report_stage(stage_callback, "Copying files to agent workspace")
    shutil.copy(PROBLEM_INSTRUCTIONS, AGENT_WORKSPACE)

    # Custom only: Copy the data/ folder also if it exists, it represents essential data that the application should work with
    if PROBLEM_TYPE == "custom" and (PROBLEM_DIR / "data").exists():
        shutil.copytree(PROBLEM_DIR / "data", AGENT_WORKSPACE / "data")

    # scb only: Write an extra instruction specifying the entrypoint file
    if PROBLEM_TYPE == "scb":
        with open(AGENT_WORKSPACE / f"checkpoint_{N}.md", "a") as f:
            f.write("\n## Entrypoint file")
            f.write(f"\nThe entrypoint file must be named `{ENTRY_FILE_NAME}.py`")

    # Reflect the requirements document in the UI
    requirements_path = AGENT_WORKSPACE / f"checkpoint_{N}.md"
    with open(requirements_path, "r") as f:
        _report_requirements(
            requirements_callback,
            {requirements_path.name: f.read()},
        )

    # if N>1, also copy the previous implementation, metrics (?) and deps graph
    if N > 1:
        if PREV_IMPL.is_dir():
            shutil.copytree(
                PREV_IMPL, AGENT_WORKSPACE / "previous_implementation", symlinks=True
            )
        else:
            raise Exception(
                f"Previous implementation for checkpoint {N-1} does not exist."
            )

        # Generate the deps graph if the workflow mode is auto / human
        if WORKFLOW_MODE in [
            "human",
            "auto",
            "autoTest",
            "autoNoMetric",
            "autoAggressive",
            "autoByLayer"
        ]:
            subprocess.run(
                [
                    "python",
                    "scripts/deps_graph.py",
                    AGENT_WORKSPACE / "previous_implementation",
                    AGENT_WORKSPACE / "deps_graphs",
                ],
                check=True,
            )

            # Extract only the json and svg
            shutil.copy(
                AGENT_WORKSPACE / "deps_graphs" / "deps_graph.json",
                AGENT_WORKSPACE / "current_deps_graph.json",
            )

            shutil.copy(
                AGENT_WORKSPACE / "deps_graphs" / "deps_graph.svg",
                AGENT_WORKSPACE / "original_deps_graph.svg",
            )

            shutil.copy(
                AGENT_WORKSPACE / "deps_graphs" / "deps_graph.json",
                AGENT_WORKSPACE / "original_deps_graph.json",
            )

            shutil.copy(
                AGENT_WORKSPACE / "deps_graphs" / "matrix.json",
                AGENT_WORKSPACE / "original_matrix.json",
            )

            shutil.copy(
                AGENT_WORKSPACE / "deps_graphs" / "matrix.png",
                AGENT_WORKSPACE / "original_matrix.png",
            )

            # Remove the temp deps_graph/ directory
            shutil.rmtree(AGENT_WORKSPACE / "deps_graphs")

        # After the orignal deps graph generated, reflect it in the UI
        _report_deps_graph(
            deps_graph_callback, get_formatted_deps_graph(AGENT_WORKSPACE)
        )

    # copy the rubrics md file (Not used, for LLM to analyze code using 5 aspects only)
    # shutil.copy("prompts/agent_prompts/rubrics.md", AGENT_WORKSPACE / "rubrics.md")

    # Step 4: Sign in to the agent
    print("[MAIN 4/8] Coding agent sign in")
    if not logged_in:
        login = CodexLogin()
        link = login.auth_url
        print(link)

        _report_stage(stage_callback, f"Coding agent sign in (Double click)\n{link}")

        # Note that it is currently very difficult to add multi line / url /
        # Dynamic {url && ELEMENTS} type to the UI

        # suspense and wait for login results
        login.wait()

    # Step 5: Volume mount
    print("[MAIN 5/8] Agent workspace volume mount")
    _report_stage(stage_callback, "Agent workspace volume mount")
    agent_workspace_abs = str(AGENT_WORKSPACE.resolve())
    executor = BwrapExecutor(agent_workspace_abs)

    # ================ MAIN WORKFLOW BEGINS ================
    print("[MAIN 6/8] Main workflow")
    _report_stage(stage_callback, "Starting main workflow")

    # Before coding, write black box tests
    if WORKFLOW_MODE == "autoTest":
        print(f"========== WRITING TESTS BEFORE IMPL ==========")
        _report_stage(stage_callback, "Writing tests before implementation")
        output = get_prompt_and_run_agent(executor, "black_box_test_writer", N)
        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)

        # Move the test suites outside the agent workspace so not to leak it
        shutil.move(AGENT_WORKSPACE / "tests", AGENT_TEST_STORAGE)

        # Remove the agent_report.json - the tests data must not be leaked
        (AGENT_WORKSPACE / "agent_report.json").unlink()

        # Remove the pytest cache file -- do not leak test intention
        pytest_cache = AGENT_WORKSPACE / ".pytest_cache"
        if pytest_cache.exists():
            shutil.rmtree(pytest_cache)

    # Before coding, generate a test blueprint
    # if HAS_TESTER:
    #     print(f"========== CREATING TEST BLUEPRINT ==========")
    #     test_plan_result = get_prompt_and_run_agent(executor, "test_planner", N)
    #     print(test_plan_result)

    #     # Move the test blueprint out of the agent workspace so the coder and designer agents cant see it
    #     shutil.move(AGENT_WORKSPACE / "test_blueprint.json", AGENT_TEST_STORAGE)

    #     # Remove the agent_report.json - the tests data must not be leaked
    #     (AGENT_WORKSPACE / "agent_report.json").unlink()

    # if the mode is no design, jump straight to implementation
    if WORKFLOW_MODE == "noDesign":
        print(f"========== CODING ALL MODULES ==========")
        _report_stage(stage_callback, "Coding all modules")
        output = get_prompt_and_run_agent(executor, "no_design_coder", N)
        # reflect in the UI the agent output
        _report_agent_response(agent_response_callback, output)
        # format code
        _format_code(AGENT_WORKSPACE)

        _report_design_or_impl(
            design_or_impl_callback, get_formatted_implementation(AGENT_WORKSPACE)
        )

        # Create a snapshot of the agent report at this point (We want to know the agent's log when IMPLEMENTING the code)
        # as the agent_report would get overridden below
        shutil.copy(
            AGENT_WORKSPACE / "agent_report.json",
            AGENT_WORKSPACE / "implementation_report.json",
        )

    elif WORKFLOW_MODE in [
        "auto",
        "autoNoMetric",
        "autoTest",
        "human",
        "autoAggressive",
        "autoByLayer"
    ]:
        # Initial decomposer agent
        # Run these inside the bind mounted space
        _decomposer_analyzer_loop(
            executor=executor,
            checkpoint_number=N,
            threshold=DA_LOOP_THRESHOLD_BEFORE_IMPL,
            agent_workspace=AGENT_WORKSPACE,
            stage_callback=stage_callback,
            design_or_impl_callback=design_or_impl_callback,
            analyzer_suggestions_callback=analyzer_suggestions_callback,
            deps_graph_callback=deps_graph_callback,
            agent_response_callback=agent_response_callback,
        )

        # Run the BFS
        print(f"========== MODULES TO CODE ==========")
        _report_stage(stage_callback, "Obtaining modules to code")
        with open(AGENT_WORKSPACE / "current_deps_graph.json", "r") as f:
            deps_graph_json = json.load(f)

        with open(AGENT_WORKSPACE / "current_design.json", "r") as f:
            design_json = json.load(f)

        # Obtain a list of list for modules to implement layer by layer
        modules_array = bfs_get_modules_to_implement(deps_graph_json, design_json)
        print(modules_array)

        modules_array_flattened = [
            item for sublist in modules_array for item in sublist
        ]
        print(f"Updating {len(modules_array_flattened)} modules.")

        # for the auto by layer mode, implement modules by layer 
        if WORKFLOW_MODE == "autoByLayer": 
            for i, layer in enumerate(modules_array): 
                _report_stage(
                    stage_callback,
                    f"Modular coder agent ({len(modules_array_flattened)} modules) - Layer {i+1} of {len(modules_array)} ({layer})",
                )
                output = get_prompt_and_run_agent(
                    executor, "modular_coder", N, layer
                )
                # reflect in the UI the agent output
                _report_agent_response(agent_response_callback, output)
        else: 
            # for the all at once mode, implement all modules
            _report_stage(
                stage_callback,
                f"Modular coder agent ({len(modules_array_flattened)} modules)",
            )
            output = get_prompt_and_run_agent(
                executor, "modular_coder", N, modules_array_flattened
            )
            # reflect in the UI the agent output
            _report_agent_response(agent_response_callback, output)

        # format code
        _format_code(AGENT_WORKSPACE)

        # reflect the code in the ui
        _report_design_or_impl(
            design_or_impl_callback, get_formatted_implementation(AGENT_WORKSPACE)
        )

        # After implementation:
        # clear all items inside the current_analyzer_result so the modifications here are not the design level ones we have previously addressed
        # NOT necessary - all rejections are provided by humans.
        # current_analyzer_json = AGENT_WORKSPACE / "current_analyzer_result.json"
        # if current_analyzer_json.exists():
        #     current_analyzer_json.unlink()
        # current_analyzer_json.touch()

        # Create a snapshot of the agent report at this point (We want to know the agent's log when IMPLEMENTING the code)
        # as the agent_report would get overridden below
        shutil.copy(
            AGENT_WORKSPACE / "agent_report.json",
            AGENT_WORKSPACE / "implementation_report.json",
        )

        # Refactor - Analyzer loop
        _analyzer_refactor_loop(
            executor,
            N,
            DA_LOOP_THRESHOLD_AFTER_IMPL,
            AGENT_WORKSPACE,
            stage_callback=stage_callback,
            design_or_impl_callback=design_or_impl_callback,
            analyzer_suggestions_callback=analyzer_suggestions_callback,
            deps_graph_callback=deps_graph_callback,
            agent_response_callback=agent_response_callback,
        )

    print(f"========== [MAIN 7/8] MOVING SOLUTION BACK ==========")
    _report_stage(stage_callback, "Moving solution back")

    # Check if the implementation exists
    implementation = AGENT_WORKSPACE / "implementation"
    IMPLEMENTATION_DEST = PROBLEM_IMPL_DIR / f"checkpoint_{N}"
    REPORT_DEST = REPORT_DIR / f"checkpoint_{N}.json"
    if implementation.is_dir():
        # Remove the existing implementation if it exists, otherwise the new one will be merged
        if IMPLEMENTATION_DEST.exists():
            shutil.rmtree(IMPLEMENTATION_DEST)

        # Copy back to the problem implementations folder
        shutil.copytree(
            implementation,
            IMPLEMENTATION_DEST,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns(
                ".venv", "__pycache__", "*.pyc", "node_modules"
            ),
        )
        # Also copy the agent report generated after it do its work
        REPORT_DEST.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(AGENT_WORKSPACE / "implementation_report.json", REPORT_DEST)
    else:
        raise Exception(f"Missing implementation for checkpoint {N}.")

    # scb only: run tests 
    # DISABLED currently because it takes too long. Do this in the evaluation instead! 
    # if PROBLEM_TYPE == "scb":
    #     print(f"========== [MAIN 8/8] RUNNING SCB TESTS ==========")
    #     _report_stage(stage_callback, "Running SCB tests")
    #     entrypoint = IMPLEMENTATION_DEST / f"{ENTRY_FILE_NAME}.py"

    #     # Run tests for all previous checkpoints from 1 to N: all of them should still pass
    #     for test_no in range(N, 0, -1):
    #         print(f"========== TEST FOR CHECKPOINT {test_no} ==========")
    #         test_results = pytest_scb(
    #             problem_name=PROBLEM,
    #             entrypoint_path=entrypoint,
    #             checkpoint_number_to_test_against=test_no,
    #         )
    #         print(test_results)
    #         _report_stage(
    #             stage_callback, f"Test for checkpoint {test_no}:\n{(test_results)}"
    #         )


# usage: python -m modular_main.main <problem_name> <checkpoint_number> <checkpoint_number_end>
# e.g. problem 1 8 means implement checkpoints 1,2, ... 8
def modular_workflow():
    parser = argparse.ArgumentParser()
    parser.add_argument("problem_name", help="Name of the problem")
    parser.add_argument("checkpoint_number", help="Checkpoint number")
    parser.add_argument(
        "checkpoint_number_end",
        help="Checkpoint number's end range value, inclusive. optional",
        nargs="?",
    )
    # parser.add_argument(
    #     "--ui",
    #     action="store_true",  # default = False
    #     help="Open the textual UI",
    # )
    args = parser.parse_args()

    start = args.checkpoint_number
    end = args.checkpoint_number_end if args.checkpoint_number_end else start
    start = int(start)
    end = int(end)

    # callbacks are optional: Only present in the UI mode
    def run(
        stage_callback=None,
        settings_callback=None,
        design_or_impl_callback=None,
        agent_response_callback=None,
        analyzer_suggestions_callback=None,
        requirements_callback=None,
        deps_graph_callback=None,
    ):
        for n in range(start, end + 1):
            modular_workflow_single(
                args.problem_name,
                n,
                logged_in=n != start,
                stage_callback=stage_callback,
                settings_callback=settings_callback,
                design_or_impl_callback=design_or_impl_callback,
                agent_response_callback=agent_response_callback,
                analyzer_suggestions_callback=analyzer_suggestions_callback,
                requirements_callback=requirements_callback,
                deps_graph_callback=deps_graph_callback,
            )

    if UI_ENABLED:
        from .ui import run_ui

        run_ui(
            AGENT_WORKSPACE = Path(f"agent_workspace"),  # UI does not support concurrently running for now due to lack of <i> state 
            workflow=run,
            on_quit=stop_run_agent_processes,
        )
    else:
        run()


if __name__ == "__main__":
    # run the modular workflow
    modular_workflow()
