# Return the original prompt, single agent, used in the SCB paper (modified). 
# This assumes agent_workspace already contain the respective files of the respective problem. 
# Module is a list of modules: instruction is to only implement the one module if its length == 1. 
def get_modular_coder_prompt(checkpoint_number, modules): 
    """
    The agent can read: 
    - whatever is in the agent workspace folder! 
    """ 

    # if the module has length = 0, raise exception
    if len(modules) == 0: 
        raise Exception("Empty module array passed to the modular coder.")

    venv_text = """Use a virtual environment and ensure that a 'requirements.txt' is present with any dependencies
you need to solve the problem.""" if checkpoint_number == 1 else """Keep using the same virtual environment you started with,
update 'requirements.txt' with any new dependencies you need."""

    code_quality_text = """Ensure good coding practices by:  
- Avoid functions that are too complex with too much nested if/else statements.
- Avoid the use of magic numbers when their meanings are not obvious.
- Do not access the private elements of another class."""

    import_instructions_text = """A dependency graph will be generated by pointing to the entrypoint file. 
Use flat file imports and do not add an __init__.py file inside implementation/."""

    return f"""
You are working on the following issue: checkpoint_{checkpoint_number}.md
Implement your solution in implementation/ folder.
{'Extend your solution based on previous_implementation/.' if checkpoint_number > 1 else ""}

{venv_text}

{code_quality_text}

{import_instructions_text}

Your job is to implement the following modules. Follow the design specified in `current_design.json` and import existing modules.
{'\n'.join([f'- {module}' for module in modules])}.
"""

#  the following {len(modules_to_implement)} modules: 
# {''.join([(f'- {x}\n') for x in modules_to_implement])}