"""
Shared coding instructions for easier processing of implementation code 
"""

def get_coding_instructions(checkpoint_number):
    venv_text = (
        """Use a virtual environment and ensure that a 'requirements.txt' is present with any dependencies
you need to solve the problem."""
        if checkpoint_number == 1
        else """Keep using the same virtual environment you started with,
update 'requirements.txt' with any new dependencies you need."""
    )

    return f"""
You are working on the following issue: checkpoint_{checkpoint_number}.md
Implement your solution in a separate, standalone implementation/ folder.
{'Extend your solution based on previous_implementation/ by preserving all its previous behaviours. First copy previous_imlementation/ to implementation/ and then modify the implementation/ directory from there.\n' if checkpoint_number > 1 else ""}
{venv_text}

A dependency graph will later be generated by pointing to the entrypoint file. 
Use flat file imports (do not use relative imports), and do not add an __init__.py file inside the implementation/ folder.

You may create temporary test scripts to verify the behaviour, but please remove these tests folders at the end as they are not part of the implementation. 
"""
