def get_coding_instructions(checkpoint_number):
    venv_text = """Use a virtual environment and ensure that a 'requirements.txt' is present with any dependencies
you need to solve the problem.""" if checkpoint_number == 1 else """Keep using the same virtual environment you started with,
update 'requirements.txt' with any new dependencies you need."""

    code_quality_text = """Ensure good coding practices by:  
- Avoid functions that are too complex with too much nested if/else statements.
- Avoid the use of magic numbers when their meanings are not obvious.
- Do not access the private elements of another class."""

    import_instructions_text = """A dependency graph will later be generated by pointing to the entrypoint file. 
Use flat file imports and do not add an __init__.py file inside the implementation/ folder."""

    return f"""
You are working on the following issue: checkpoint_{checkpoint_number}.md
Implement your solution in implementation/ folder.
{'Extend your solution based on previous_implementation/.' if checkpoint_number > 1 else ""}

{venv_text}

{code_quality_text}

{import_instructions_text} 
"""